/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#f54e00',
        'primary-active': '#d04200',
        ink: '#26251e',
        body: '#5a5852',
        'body-strong': '#26251e',
        muted: '#807d72',
        'muted-soft': '#a09c92',
        hairline: '#e6e5e0',
        'hairline-soft': '#efeee8',
        'hairline-strong': '#cfcdc4',
        canvas: '#f7f7f4',
        'canvas-soft': '#fafaf7',
        'surface-card': '#ffffff',
        'surface-strong': '#e6e5e0',
        'on-primary': '#ffffff',
        'semantic-error': '#cf2d56',
        'semantic-success': '#1f8a65',
        'timeline-thinking': '#dfa88f',
        'timeline-grep': '#9fc9a2',
        'timeline-read': '#9fbbe0',
        'timeline-edit': '#c0a8dd',
        'timeline-done': '#c08532',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"Fira Code"', 'monospace'],
      },
      fontSize: {
        'display-mega': ['72px', { lineHeight: '1.1', letterSpacing: '-2.16px', fontWeight: '400' }],
        'display-lg': ['36px', { lineHeight: '1.2', letterSpacing: '-0.72px', fontWeight: '400' }],
        'display-md': ['26px', { lineHeight: '1.25', letterSpacing: '-0.325px', fontWeight: '400' }],
        'display-sm': ['22px', { lineHeight: '1.3', letterSpacing: '-0.11px', fontWeight: '400' }],
        'title-md': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'title-sm': ['16px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        caption: ['13px', { lineHeight: '1.4', fontWeight: '400' }],
        'caption-upper': ['11px', { lineHeight: '1.4', fontWeight: '600', letterSpacing: '0.88px' }],
        btn: ['14px', { lineHeight: '1.0', fontWeight: '500' }],
        nav: ['14px', { lineHeight: '1.4', fontWeight: '500' }],
        code: ['13px', { lineHeight: '1.5', fontWeight: '400' }],
      },
      borderRadius: {
        none: '0px',
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        pill: '9999px',
        full: '9999px',
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        base: '16px',
        md: '20px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        section: '80px',
      },
      boxShadow: {
        none: 'none',
      },
    },
  },
  plugins: [],
};
