"""added url to the deployment

Revision ID: 234b0a391f30
Revises: a5ea9b0c575d
Create Date: 2026-07-09 18:01:51.910629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234b0a391f30'
down_revision: Union[str, Sequence[str], None] = 'a5ea9b0c575d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('deployment_url', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'deployments', ['host_port'])
    op.create_unique_constraint(None, 'deployments', ['deployment_url'])
    op.create_unique_constraint(None, 'deployments', ['container_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deployments', type_='unique')
    op.drop_constraint(None, 'deployments', type_='unique')
    op.drop_constraint(None, 'deployments', type_='unique')
    op.drop_column('deployments', 'deployment_url')
    # ### end Alembic commands ###
